In [1]:
import pandas as pd

In [2]:
# this is to retrieve and load the csv file to pandas' dataframe. This is for preliminary investigation and formatting purposes

df = pd.read_csv('portland_oregeon_crime.csv', header= 0, encoding= 'unicode_escape')
df.head(10)

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,OpenDataLat,OpenDataLon,OpenDataX,OpenDataY,Report Date,ReportMonthYear
0,3600 BLOCK OF SE KNAPP ST,17-902332,Property,Eastmoreland,1,2/20/2017,2/1/2017,0,Larceny Offenses,1,Theft From Motor Vehicle,45.470545,-122.625298,7656952.0,664817.0,2/20/2017,February 2017
1,3600 BLOCK OF SE LAMBERT ST,17-902346,Property,Eastmoreland,1,2/20/2017,2/1/2017,30,Larceny Offenses,1,Theft From Motor Vehicle,45.467028,-122.625272,7656925.0,663535.0,2/20/2017,February 2017
2,7200 BLOCK OF SE 32ND AVE,17-902450,Property,Eastmoreland,1,2/21/2017,2/1/2017,2345,Larceny Offenses,1,Theft From Motor Vehicle,45.471859,-122.630327,7655675.0,665330.0,2/22/2017,February 2017
3,6500 BLOCK OF SE 32ND AVE,17-902495,Property,Eastmoreland,1,2/21/2017,2/1/2017,2350,Larceny Offenses,1,Theft From Motor Vehicle,45.475196,-122.630444,7655677.0,666547.0,2/22/2017,February 2017
4,500 BLOCK OF N DIXON ST,17-901848,Property,Eliot,1,12/21/2016,12/1/2016,1330,Larceny Offenses,1,Theft From Motor Vehicle,45.534551,-122.671730,7645672.0,688462.0,2/11/2017,February 2017
5,2200 BLOCK OF N FLINT AVE,17-33224,Property,Eliot,1,2/2/2017,2/1/2017,1931,Larceny Offenses,1,Theft From Motor Vehicle,45.539218,-122.668789,7646471.0,690143.0,2/2/2017,February 2017
6,400 BLOCK OF N DIXON ST,17-902972,Property,Eliot,1,2/2/2017,2/1/2017,2145,Larceny Offenses,1,Theft From Motor Vehicle,45.534929,-122.670847,7645902.0,688594.0,2/2/2017,February 2017
7,1900 BLOCK OF N WILLIAMS AVE,17-901378,Property,Eliot,1,2/3/2017,2/1/2017,1005,Larceny Offenses,1,Theft From Motor Vehicle,45.536801,-122.666776,7646963.0,689248.0,2/3/2017,February 2017
8,500 BLOCK OF NE SACRAMENTO ST,17-36779,Property,Eliot,1,2/6/2017,2/1/2017,0,Larceny Offenses,1,Theft From Motor Vehicle,45.539513,-122.660117,7648695.0,690191.0,2/6/2017,February 2017
9,1500 BLOCK OF N INTERSTATE AVE,17-37320,Property,Eliot,1,2/6/2017,2/1/2017,1620,Larceny Offenses,1,Theft From Motor Vehicle,45.533491,-122.672174,7645548.0,688079.0,2/6/2017,February 2017

In [3]:
# this is to convert MM/DD/YYYY to YYYY-MM-DD on the Occur Date column
df['Occur Date'] = pd.to_datetime(df['Occur Date']).dt.strftime('%Y-%m-%d')

In [4]:
df.head(10)

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,OpenDataLat,OpenDataLon,OpenDataX,OpenDataY,Report Date,ReportMonthYear
0,3600 BLOCK OF SE KNAPP ST,17-902332,Property,Eastmoreland,1,2017-02-20,2/1/2017,0,Larceny Offenses,1,Theft From Motor Vehicle,45.470545,-122.625298,7656952.0,664817.0,2/20/2017,February 2017
1,3600 BLOCK OF SE LAMBERT ST,17-902346,Property,Eastmoreland,1,2017-02-20,2/1/2017,30,Larceny Offenses,1,Theft From Motor Vehicle,45.467028,-122.625272,7656925.0,663535.0,2/20/2017,February 2017
2,7200 BLOCK OF SE 32ND AVE,17-902450,Property,Eastmoreland,1,2017-02-21,2/1/2017,2345,Larceny Offenses,1,Theft From Motor Vehicle,45.471859,-122.630327,7655675.0,665330.0,2/22/2017,February 2017
3,6500 BLOCK OF SE 32ND AVE,17-902495,Property,Eastmoreland,1,2017-02-21,2/1/2017,2350,Larceny Offenses,1,Theft From Motor Vehicle,45.475196,-122.630444,7655677.0,666547.0,2/22/2017,February 2017
4,500 BLOCK OF N DIXON ST,17-901848,Property,Eliot,1,2016-12-21,12/1/2016,1330,Larceny Offenses,1,Theft From Motor Vehicle,45.534551,-122.671730,7645672.0,688462.0,2/11/2017,February 2017
5,2200 BLOCK OF N FLINT AVE,17-33224,Property,Eliot,1,2017-02-02,2/1/2017,1931,Larceny Offenses,1,Theft From Motor Vehicle,45.539218,-122.668789,7646471.0,690143.0,2/2/2017,February 2017
6,400 BLOCK OF N DIXON ST,17-902972,Property,Eliot,1,2017-02-02,2/1/2017,2145,Larceny Offenses,1,Theft From Motor Vehicle,45.534929,-122.670847,7645902.0,688594.0,2/2/2017,February 2017
7,1900 BLOCK OF N WILLIAMS AVE,17-901378,Property,Eliot,1,2017-02-03,2/1/2017,1005,Larceny Offenses,1,Theft From Motor Vehicle,45.536801,-122.666776,7646963.0,689248.0,2/3/2017,February 2017
8,500 BLOCK OF NE SACRAMENTO ST,17-36779,Property,Eliot,1,2017-02-06,2/1/2017,0,Larceny Offenses,1,Theft From Motor Vehicle,45.539513,-122.660117,7648695.0,690191.0,2/6/2017,February 2017
9,1500 BLOCK OF N INTERSTATE AVE,17-37320,Property,Eliot,1,2017-02-06,2/1/2017,1620,Larceny Offenses,1,Theft From Motor Vehicle,45.533491,-122.672174,7645548.0,688079.0,2/6/2017,February 2017

In [5]:
# remove all NaN values in Address column to Not Available 
df['Address'].fillna('NOT AVAILABLE', inplace = True)

# remove all NaN values in Neighborhood column to Not Available 
df['Neighborhood'].fillna('NOT AVAILABLE', inplace = True)

# remove all NaN values in OpenDataLat column to Not Available 
df['OpenDataLat'].fillna('NOT AVAILABLE', inplace = True)

# remove all NaN values in OpenDataLon column to Not Available 
df['OpenDataLon'].fillna('NOT AVAILABLE', inplace = True)

In [6]:
# to display and check if NaN values have been converted
df.head(20)

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,OpenDataLat,OpenDataLon,OpenDataX,OpenDataY,Report Date,ReportMonthYear
0,3600 BLOCK OF SE KNAPP ST,17-902332,Property,Eastmoreland,1,2017-02-20,2/1/2017,0,Larceny Offenses,1,Theft From Motor Vehicle,45.4705,-122.625,7656952.0,664817.0,2/20/2017,February 2017
1,3600 BLOCK OF SE LAMBERT ST,17-902346,Property,Eastmoreland,1,2017-02-20,2/1/2017,30,Larceny Offenses,1,Theft From Motor Vehicle,45.467,-122.625,7656925.0,663535.0,2/20/2017,February 2017
2,7200 BLOCK OF SE 32ND AVE,17-902450,Property,Eastmoreland,1,2017-02-21,2/1/2017,2345,Larceny Offenses,1,Theft From Motor Vehicle,45.4719,-122.63,7655675.0,665330.0,2/22/2017,February 2017
3,6500 BLOCK OF SE 32ND AVE,17-902495,Property,Eastmoreland,1,2017-02-21,2/1/2017,2350,Larceny Offenses,1,Theft From Motor Vehicle,45.4752,-122.63,7655677.0,666547.0,2/22/2017,February 2017
4,500 BLOCK OF N DIXON ST,17-901848,Property,Eliot,1,2016-12-21,12/1/2016,1330,Larceny Offenses,1,Theft From Motor Vehicle,45.5346,-122.672,7645672.0,688462.0,2/11/2017,February 2017
5,2200 BLOCK OF N FLINT AVE,17-33224,Property,Eliot,1,2017-02-02,2/1/2017,1931,Larceny Offenses,1,Theft From Motor Vehicle,45.5392,-122.669,7646471.0,690143.0,2/2/2017,February 2017
6,400 BLOCK OF N DIXON ST,17-902972,Property,Eliot,1,2017-02-02,2/1/2017,2145,Larceny Offenses,1,Theft From Motor Vehicle,45.5349,-122.671,7645902.0,688594.0,2/2/2017,February 2017
7,1900 BLOCK OF N WILLIAMS AVE,17-901378,Property,Eliot,1,2017-02-03,2/1/2017,1005,Larceny Offenses,1,Theft From Motor Vehicle,45.5368,-122.667,7646963.0,689248.0,2/3/2017,February 2017
8,500 BLOCK OF NE SACRAMENTO ST,17-36779,Property,Eliot,1,2017-02-06,2/1/2017,0,Larceny Offenses,1,Theft From Motor Vehicle,45.5395,-122.66,7648695.0,690191.0,2/6/2017,February 2017
9,1500 BLOCK OF N INTERSTATE AVE,17-37320,Property,Eliot,1,2017-02-06,2/1/2017,1620,Larceny Offenses,1,Theft From Motor Vehicle,45.5335,-122.672,7645548.0,688079.0,2/6/2017,February 2017
10,300 BLOCK OF NE RUSSELL ST,17-37361,Property,Eliot,1,2017-02-06,2/1/2017,1900,Larceny Offenses,1,Theft From Motor Vehicle,45.541,-122.662,7648220.0,690733.0,2/6/2017,February 2017
11,3300 BLOCK OF NE RODNEY AVE,17-37647,Property,Eliot,1,2017-02-07,2/1/2017,0,Larceny Offenses,1,Theft From Motor Vehicle,45.5471,-122.664,7647733.0,692991.0,2/7/2017,February 2017
12,2300 BLOCK OF NE RODNEY AVE,17-901662,Property,Eliot,1,2017-02-06,2/1/2017,2000,Larceny Offenses,1,Theft From Motor Vehicle,45.5397,-122.664,7647646.0,690298.0,2/7/2017,February 2017
13,N VANCOUVER AVE / N IVY ST,17-38875,Property,Eliot,1,2017-02-07,2/1/2017,1200,Larceny Offenses,1,Theft From Motor Vehicle,45.5475,-122.668,7646764.0,693145.0,2/8/2017,February 2017
14,NE 1ST AVE / NE SCHUYLER ST,17-901773,Property,Eliot,1,2017-02-07,2/1/2017,1250,Larceny Offenses,1,Theft From Motor Vehicle,45.5358,-122.665,7647488.0,688869.0,2/9/2017,February 2017
15,0 BLOCK OF NE SAN RAFAEL ST,17-901819,Property,Eliot,1,2017-02-09,2/1/2017,5,Larceny Offenses,1,Theft From Motor Vehicle,45.5371,-122.665,7647307.0,689356.0,2/11/2017,February 2017
16,2200 BLOCK OF N FLINT AVE,17-901811,Property,Eliot,1,2017-02-10,2/1/2017,2010,Larceny Offenses,1,Theft From Motor Vehicle,45.5392,-122.669,7646471.0,690143.0,2/11/2017,February 2017
17,300 BLOCK OF N DIXON ST,17-43927,Property,Eliot,1,2017-02-11,2/1/2017,1800,Larceny Offenses,1,Theft From Motor Vehicle,45.5354,-122.67,7646090.0,688774.0,2/13/2017,February 2017
18,600 BLOCK OF NE BROADWAY,17-901898,Property,Eliot,1,2017-02-12,2/1/2017,2100,Larceny Offenses,1,Theft From Motor Vehicle,45.5351,-122.659,7648909.0,688580.0,2/13/2017,February 2017
19,2600 BLOCK OF NE MARTIN LUTHER KING JR BLVD,17-901939,Property,Eliot,1,2017-02-14,2/1/2017,200,Larceny Offenses,1,Theft From Motor Vehicle,45.5416,-122.662,7648350.0,690952.0,2/14/2017,February 2017

In [7]:
# this is to remove all the columns which is not needed
df = df.drop(columns=['Offense Category' , 'Crime Against', 'Number of Records', 'Occur Month Year', 'Occur Time', 'Offense Count',  'OpenDataX', 'OpenDataY', 'Report Date', 'ReportMonthYear'])

In [8]:
# to check if the data has been cleaned 
df.head(5)

,Address,Case Number,Neighborhood,Occur Date,Offense Type,OpenDataLat,OpenDataLon
0,3600 BLOCK OF SE KNAPP ST,17-902332,Eastmoreland,2017-02-20,Theft From Motor Vehicle,45.4705,-122.625
1,3600 BLOCK OF SE LAMBERT ST,17-902346,Eastmoreland,2017-02-20,Theft From Motor Vehicle,45.467,-122.625
2,7200 BLOCK OF SE 32ND AVE,17-902450,Eastmoreland,2017-02-21,Theft From Motor Vehicle,45.4719,-122.63
3,6500 BLOCK OF SE 32ND AVE,17-902495,Eastmoreland,2017-02-21,Theft From Motor Vehicle,45.4752,-122.63
4,500 BLOCK OF N DIXON ST,17-901848,Eliot,2016-12-21,Theft From Motor Vehicle,45.5346,-122.672

In [9]:
# this is to replace all the - with an empty space on the case number column
df['Case Number'] = df['Case Number'].apply(lambda x: x.replace('-',''))

In [10]:
# drop duplicate in Case Number
df = df.drop_duplicates(['Case Number'], keep=False)

In [11]:
# save and export the edited .csv file 
df.to_csv('portland-oregon-crime-cleaned.csv', index = False)